
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DEGAL = 26;
  public static final int EGAL = 25;
  public static final int DAO = 7;
  public static final int ETAT = 30;
  public static final int DSCO = 15;
  public static final int DSO = 11;
  public static final int DATE = 3;
  public static final int DAF = 8;
  public static final int nom = 19;
  public static final int MSG = 31;
  public static final int DSCF = 16;
  public static final int cm = 32;
  public static final int DSF = 12;
  public static final int PV = 28;
  public static final int DP = 27;
  public static final int AO = 21;
  public static final int PT = 18;
  public static final int H = 29;
  public static final int PO = 23;
  public static final int EOF = 0;
  public static final int AF = 22;
  public static final int APPAREIL = 20;
  public static final int error = 1;
  public static final int PDO = 4;
  public static final int PF = 24;
  public static final int DCO = 13;
  public static final int VG = 17;
  public static final int ACTION = 2;
  public static final int DIO = 9;
  public static final int COTE = 6;
  public static final int PDF = 5;
  public static final int DCF = 14;
  public static final int DIF = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACTION",
  "DATE",
  "PDO",
  "PDF",
  "COTE",
  "DAO",
  "DAF",
  "DIO",
  "DIF",
  "DSO",
  "DSF",
  "DCO",
  "DCF",
  "DSCO",
  "DSCF",
  "VG",
  "PT",
  "nom",
  "APPAREIL",
  "AO",
  "AF",
  "PO",
  "PF",
  "EGAL",
  "DEGAL",
  "DP",
  "PV",
  "H",
  "ETAT",
  "MSG",
  "cm"
  };
}

